### ISSUE TITLE
Having trouble getting sensor data

### ISSUE THREAD

**Issue by OptimalPaul** [NordicPlayground/Nordic-Thingy52-mesh-demo#1]
I seem to have everything working except for the fact that when the servers are calling access_model_publish for updated sensor data I never see that on the bridge/client. The access model callback is never triggered.  Does the bridge/client need to do some subscribing to be able to see these messages?

**Comment by rick1082** [comment]
Hello OptimalPaul, since the config client on the bridge has configured nodes to publish messages back to the simple Thingy client model on the bridge during the configuration. So once the bridge sends "sensor feedback rate config" to a node, a node will publish the sensor feedback to the bridge. And if user turning on the TX notification, the sensor information will show up. And sorry for the unclear in the document, I will update it.

**Comment by OptimalPaul** [comment]
Hmmm.. I have notification turned on.  I am getting the command responses back from the bridge node just not the sensor readings.

**Comment by rick1082** [comment]
Hello @OptimalPaul, would it possible for you to get back the sensor reading information? I have updated the document, hope it can do help.
